# Generated by Django 4.2.2 on 2023-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_alter_blog_full_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="tutocategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="")),
                ("description", models.TextField(max_length=50000)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
    ]
