# Generated by Django 4.2.2 on 2023-08-22 15:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_tutocategorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="full_description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
