# Generated by Django 4.2.2 on 2023-08-22 16:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_alter_blog_description_alter_blog_full_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursphp",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
