# Generated by Django 4.2.2 on 2023-08-22 16:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0020_alter_coursphp_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courscsharp",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="coursdart",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="coursjava",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="coursjavascript",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="courspython",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
