# Generated by Django 4.2.2 on 2023-08-22 16:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0021_alter_courscsharp_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illustrator",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="photoshop",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
