# Generated by Django 4.2.2 on 2023-08-24 14:36

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0022_alter_illustrator_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
