# Generated by Django 4.2.2 on 2023-08-24 15:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0023_alter_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="illustrator",
            name="description",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="photoshop",
            name="description",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(max_length=50000),
        ),
    ]
